//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LekarskaOrdinacijaCodeMedic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Usluga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usluga()
        {
            this.Zakazivanje = new HashSet<Zakazivanje>();
        }
    
        public int id_usluga { get; set; }
        [DisplayName("Naziv usluge")]
        public string vrsta_usluge { get; set; }
        public Nullable<int> cena { get; set; }
        public Nullable<int> Id_specijalizacije { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakazivanje> Zakazivanje { get; set; }
        public virtual Specijalizacija Specijalizacija { get; set; }
    }
}
