//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LekarskaOrdinacijaCodeMedic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Zakazivanje
    {
        public int id_zakazivanja { get; set; }
        public string id_korisnika { get; set; }
        public Nullable<int> id_usluga { get; set; }
        [DisplayName("Vreme termina")]
        public Nullable<System.TimeSpan> vreme_pocetka { get; set; }
        [DisplayName("Datum termina")]
        public Nullable<System.DateTime> vreme_zavrsetka { get; set; }
        public string beleska { get; set; }
        public string lekar_id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual Usluga Usluga { get; set; }
    }
}
